<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Final Testing Documentation</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #111827;
            line-height: 1.5;
        }

        .header {
            text-align: center;
            border-bottom: 3px solid #111827;
            padding-bottom: 12px;
            margin-bottom: 18px;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 4px;
        }

        .subtitle {
            font-size: 13px;
            color: #4b5563;
        }

        .muted {
            color: #6b7280;
            font-size: 10px;
        }

        .section {
            margin-bottom: 18px;
            page-break-inside: avoid;
        }

        .section-title {
            font-size: 16px;
            font-weight: bold;
            background: #111827;
            color: #ffffff;
            padding: 7px 9px;
            margin-bottom: 8px;
        }

        .summary-table,
        .stats-table,
        .module-table,
        .checklist-table,
        .issues-table {
            width: 100%;
            border-collapse: collapse;
        }

        .summary-table td,
        .stats-table td,
        .module-table th,
        .module-table td,
        .checklist-table th,
        .checklist-table td,
        .issues-table th,
        .issues-table td {
            border: 1px solid #d1d5db;
            padding: 6px;
            vertical-align: top;
        }

        .summary-table td {
            text-align: center;
        }

        .summary-label {
            font-size: 10px;
            color: #6b7280;
            font-weight: bold;
        }

        .summary-value {
            font-size: 20px;
            font-weight: bold;
            color: #111827;
        }

        .stats-label {
            font-weight: bold;
            background: #f3f4f6;
            width: 25%;
        }

        .module-table th,
        .checklist-table th,
        .issues-table th {
            background: #f3f4f6;
            font-weight: bold;
            color: #111827;
            text-align: left;
        }

        .badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 20px;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .badge-passed,
        .badge-ready,
        .badge-handled {
            background: #dcfce7;
            color: #166534;
        }

        .badge-failed {
            background: #fee2e2;
            color: #991b1b;
        }

        .badge-pending {
            background: #fef3c7;
            color: #92400e;
        }

        .readiness {
            border: 2px solid #16a34a;
            background: #f0fdf4;
            padding: 12px;
            border-radius: 6px;
        }

        .readiness-title {
            font-size: 15px;
            font-weight: bold;
            color: #166534;
            margin-bottom: 4px;
        }

        .footer {
            margin-top: 24px;
            border-top: 1px solid #d1d5db;
            padding-top: 8px;
            font-size: 10px;
            color: #6b7280;
            text-align: center;
        }

        .page-break {
            page-break-before: always;
        }

        .text-center {
            text-align: center;
        }

        .small {
            font-size: 10px;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">Final Testing Documentation</div>
        <div class="subtitle">
            Smart Event Invitation & Planning System
        </div>

        <div class="muted">
            Generated At:
            {{ $generatedAt ? $generatedAt->format('Y-m-d h:i A') : 'N/A' }}

            @if (!empty($generatedBy))
                |
                Generated By:
                {{ $generatedBy->name ?? 'N/A' }}
                @if (!empty($generatedBy->email))
                    ({{ $generatedBy->email }})
                @endif
            @endif
        </div>
    </div>

    <div class="section">
        <div class="section-title">1. System Overview</div>

        <p>
            This document summarizes the final testing status of the Smart Event Invitation & Planning System.
            The system allows authenticated organizers to create events, generate public invitation links,
            collect RSVP responses, manage guests, track event planning activities, handle check-ins,
            monitor reminders, generate reports, and allow Super Admin users to monitor the entire platform.
        </p>

        <table class="stats-table">
            <tr>
                <td class="stats-label">Total Events</td>
                <td>{{ $systemStats['total_events'] ?? 0 }}</td>

                <td class="stats-label">Draft Events</td>
                <td>{{ $systemStats['draft_events'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Active Events</td>
                <td>{{ $systemStats['active_events'] ?? 0 }}</td>

                <td class="stats-label">Completed Events</td>
                <td>{{ $systemStats['completed_events'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Cancelled Events</td>
                <td>{{ $systemStats['cancelled_events'] ?? 0 }}</td>

                <td class="stats-label">Total Users</td>
                <td>{{ $systemStats['total_users'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Guests</td>
                <td>{{ $systemStats['total_guests'] ?? 0 }}</td>

                <td class="stats-label">Total Invitations</td>
                <td>{{ $systemStats['total_invitations'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total RSVP Questions</td>
                <td>{{ $systemStats['total_questions'] ?? 0 }}</td>

                <td class="stats-label">Total QA Checks</td>
                <td>{{ $systemStats['total_qa_checks'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Activity Logs</td>
                <td>{{ $systemStats['total_activity_logs'] ?? 0 }}</td>

                <td class="stats-label">Completion Percentage</td>
                <td>{{ $summary['completion_percentage'] ?? 0 }}%</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">2. Testing Summary</div>

        <table class="summary-table">
            <tr>
                <td>
                    <div class="summary-label">Total Tests</div>
                    <div class="summary-value">{{ $summary['total_tests'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">Passed</div>
                    <div class="summary-value">{{ $summary['passed_tests'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">Failed</div>
                    <div class="summary-value">{{ $summary['failed_tests'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">Pending</div>
                    <div class="summary-value">{{ $summary['pending_tests'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">Completion</div>
                    <div class="summary-value">{{ $summary['completion_percentage'] ?? 0 }}%</div>
                </td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">3. Final Readiness Status</div>

        <div class="readiness">
            <div class="readiness-title">
                {{ $readiness['status'] ?? 'N/A' }}
            </div>

            <div>
                {{ $readiness['message'] ?? 'N/A' }}
            </div>
        </div>
    </div>

    <div class="section page-break">
        <div class="section-title">4. Module Testing Table</div>

        <table class="module-table">
            <thead>
                <tr>
                    <th style="width: 3%;">#</th>
                    <th style="width: 15%;">Module</th>
                    <th style="width: 10%;">Category</th>
                    <th style="width: 25%;">Test Case</th>
                    <th style="width: 25%;">Expected Result</th>
                    <th style="width: 8%;">Status</th>
                    <th style="width: 14%;">Remarks</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($modules as $index => $module)
                    <tr>
                        <td class="text-center">{{ $index + 1 }}</td>

                        <td>
                            <strong>{{ $module['module'] ?? 'N/A' }}</strong>
                        </td>

                        <td>{{ $module['category'] ?? 'N/A' }}</td>

                        <td>{{ $module['test_case'] ?? 'N/A' }}</td>

                        <td>{{ $module['expected_result'] ?? 'N/A' }}</td>

                        <td class="text-center">
                            <span class="badge badge-{{ $module['status'] ?? 'pending' }}">
                                {{ $module['status'] ?? 'pending' }}
                            </span>
                        </td>

                        <td>{{ $module['remarks'] ?? 'N/A' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" class="text-center">
                            No testing modules found.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section page-break">
        <div class="section-title">5. Final Demo Checklist</div>

        <table class="checklist-table">
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    <th style="width: 25%;">Step</th>
                    <th style="width: 55%;">Description</th>
                    <th style="width: 15%;">Status</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($demoChecklist as $index => $item)
                    <tr>
                        <td class="text-center">{{ $index + 1 }}</td>

                        <td>
                            <strong>{{ $item['step'] ?? 'N/A' }}</strong>
                        </td>

                        <td>{{ $item['description'] ?? 'N/A' }}</td>

                        <td class="text-center">
                            <span class="badge badge-{{ $item['status'] ?? 'pending' }}">
                                {{ $item['status'] ?? 'pending' }}
                            </span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4" class="text-center">
                            No demo checklist items found.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">6. Known Issues / Remarks</div>

        <table class="issues-table">
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    <th style="width: 25%;">Issue / Remark</th>
                    <th style="width: 55%;">Description</th>
                    <th style="width: 15%;">Status</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($knownIssues as $index => $issue)
                    <tr>
                        <td class="text-center">{{ $index + 1 }}</td>

                        <td>
                            <strong>{{ $issue['title'] ?? 'N/A' }}</strong>
                        </td>

                        <td>{{ $issue['description'] ?? 'N/A' }}</td>

                        <td class="text-center">
                            <span class="badge badge-{{ $issue['status'] ?? 'pending' }}">
                                {{ $issue['status'] ?? 'pending' }}
                            </span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4" class="text-center">
                            No known issues listed.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">7. Final Conclusion</div>

        <p>
            Based on the completed module tests, the Smart Event Invitation & Planning System is ready for final
            demonstration and project submission. The tested features cover authentication, role-based access,
            event creation, guest handling, public invitations, RSVP collection, check-ins, follow-ups, planning tools,
            reminders, activity logging, dashboard analytics, PDF reporting, event lifecycle controls, documentation,
            and Super Admin monitoring.
        </p>

        <p>
            The final testing process confirms that the major functional areas of the system are working as expected.
            Any future improvements can focus on advanced automation, enhanced UI polish, email/SMS integrations,
            and production deployment hardening.
        </p>
    </div>

    <div class="footer">
        Smart Event Invitation & Planning System | Final Testing Documentation PDF
    </div>
</body>
</html>
