<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Master Final Submission PDF</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #111827;
            line-height: 1.5;
        }

        .header {
            text-align: center;
            border-bottom: 3px solid #111827;
            padding-bottom: 12px;
            margin-bottom: 18px;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 4px;
        }

        .subtitle {
            font-size: 13px;
            color: #4b5563;
        }

        .muted {
            color: #6b7280;
            font-size: 10px;
        }

        .section {
            margin-bottom: 18px;
            page-break-inside: avoid;
        }

        .section-title {
            font-size: 15px;
            font-weight: bold;
            background: #111827;
            color: #ffffff;
            padding: 7px 9px;
            margin-bottom: 8px;
        }

        .info-table,
        .stats-table,
        .documents-table,
        .checklist-table,
        .flow-table {
            width: 100%;
            border-collapse: collapse;
        }

        .info-table td,
        .stats-table td,
        .documents-table th,
        .documents-table td,
        .checklist-table th,
        .checklist-table td,
        .flow-table th,
        .flow-table td {
            border: 1px solid #d1d5db;
            padding: 6px;
            vertical-align: top;
        }

        .label {
            font-weight: bold;
            background: #f3f4f6;
            width: 24%;
        }

        .stats-label {
            font-weight: bold;
            background: #f3f4f6;
            width: 25%;
        }

        .documents-table th,
        .checklist-table th,
        .flow-table th {
            background: #f3f4f6;
            color: #111827;
            text-align: left;
        }

        .badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 20px;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
            background: #dcfce7;
            color: #166534;
        }

        .badge-pdf {
            background: #fee2e2;
            color: #991b1b;
        }

        .badge-page {
            background: #ede9fe;
            color: #5b21b6;
        }

        .readiness {
            border: 2px solid #16a34a;
            background: #f0fdf4;
            padding: 12px;
            border-radius: 6px;
        }

        .readiness-title {
            font-size: 15px;
            font-weight: bold;
            color: #166534;
            margin-bottom: 4px;
        }

        ul {
            margin-top: 4px;
            margin-bottom: 4px;
            padding-left: 20px;
        }

        li {
            margin-bottom: 3px;
        }

        .page-break {
            page-break-before: always;
        }

        .footer {
            margin-top: 24px;
            border-top: 1px solid #d1d5db;
            padding-top: 8px;
            font-size: 10px;
            color: #6b7280;
            text-align: center;
        }

        .text-center {
            text-align: center;
        }

        .small {
            font-size: 10px;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">Master Final Submission PDF</div>

        <div class="subtitle">
            {{ $project['name'] ?? 'Smart Event Invitation & Planning System' }}
        </div>

        <div class="muted">
            Generated At:
            {{ $generatedAt ? $generatedAt->format('Y-m-d h:i A') : 'N/A' }}

            @if (!empty($generatedBy))
                |
                Generated By:
                {{ $generatedBy->name ?? 'N/A' }}

                @if (!empty($generatedBy->email))
                    ({{ $generatedBy->email }})
                @endif
            @endif
        </div>
    </div>

    <div class="section">
        <div class="section-title">1. Project Summary</div>

        <table class="info-table">
            <tr>
                <td class="label">Project Name</td>
                <td>{{ $project['name'] ?? 'N/A' }}</td>
            </tr>

            <tr>
                <td class="label">Status</td>
                <td>
                    <span class="badge">
                        {{ $project['status'] ?? 'N/A' }}
                    </span>
                </td>
            </tr>

            <tr>
                <td class="label">Summary</td>
                <td>{{ $project['summary'] ?? 'N/A' }}</td>
            </tr>

            <tr>
                <td class="label">Local URL</td>
                <td>{{ $project['local_url'] ?? 'N/A' }}</td>
            </tr>

            <tr>
                <td class="label">Database</td>
                <td>{{ $project['database'] ?? 'N/A' }}</td>
            </tr>

            <tr>
                <td class="label">Environment</td>
                <td>{{ $project['environment'] ?? 'N/A' }}</td>
            </tr>

            <tr>
                <td class="label">Technology Stack</td>
                <td>
                    <ul>
                        @foreach (($project['technology'] ?? []) as $technology)
                            <li>{{ $technology }}</li>
                        @endforeach
                    </ul>
                </td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">2. Final Readiness</div>

        <div class="readiness">
            <div class="readiness-title">
                Ready for Final Demo / Submission
            </div>

            <div>
                The Smart Event Invitation & Planning System includes the main organizer modules,
                public invitation workflow, Super Admin monitoring pages, final testing documentation,
                handover documentation, and PDF reports required for final project submission.
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">3. System Statistics</div>

        <table class="stats-table">
            <tr>
                <td class="stats-label">Total Events</td>
                <td>{{ $stats['total_events'] ?? 0 }}</td>

                <td class="stats-label">Draft Events</td>
                <td>{{ $stats['draft_events'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Active Events</td>
                <td>{{ $stats['active_events'] ?? 0 }}</td>

                <td class="stats-label">Completed Events</td>
                <td>{{ $stats['completed_events'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Cancelled Events</td>
                <td>{{ $stats['cancelled_events'] ?? 0 }}</td>

                <td class="stats-label">Total Users</td>
                <td>{{ $stats['total_users'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Guests</td>
                <td>{{ $stats['total_guests'] ?? 0 }}</td>

                <td class="stats-label">Total Invitations</td>
                <td>{{ $stats['total_invitations'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Questions</td>
                <td>{{ $stats['total_questions'] ?? 0 }}</td>

                <td class="stats-label">Total Answers</td>
                <td>{{ $stats['total_answers'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Tasks</td>
                <td>{{ $stats['total_tasks'] ?? 0 }}</td>

                <td class="stats-label">Total Expenses</td>
                <td>{{ $stats['total_expenses'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Vendors</td>
                <td>{{ $stats['total_vendors'] ?? 0 }}</td>

                <td class="stats-label">Total Schedules</td>
                <td>{{ $stats['total_schedules'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Staff</td>
                <td>{{ $stats['total_staff'] ?? 0 }}</td>

                <td class="stats-label">Total Reminders</td>
                <td>{{ $stats['total_reminders'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Reminder Logs</td>
                <td>{{ $stats['total_reminder_logs'] ?? 0 }}</td>

                <td class="stats-label">Total QA Checks</td>
                <td>{{ $stats['total_qa_checks'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Activity Logs</td>
                <td>{{ $stats['total_activity_logs'] ?? 0 }}</td>

                <td class="stats-label">Report Type</td>
                <td>Master Final Submission PDF</td>
            </tr>
        </table>
    </div>

    <div class="section page-break">
        <div class="section-title">4. Final Documents</div>

        <table class="documents-table">
            <thead>
                <tr>
                    <th style="width: 25%;">Document</th>
                    <th style="width: 50%;">Description</th>
                    <th style="width: 10%;">Type</th>
                    <th style="width: 15%;">Status</th>
                </tr>
            </thead>

            <tbody>
                @forelse (($finalDocuments ?? []) as $document)
                    <tr>
                        <td><strong>{{ $document['title'] ?? 'N/A' }}</strong></td>
                        <td>{{ $document['description'] ?? 'N/A' }}</td>
                        <td class="text-center">
                            @php
                                $type = strtolower($document['type'] ?? 'page');
                                $badgeClass = $type === 'pdf' ? 'badge-pdf' : 'badge-page';
                            @endphp

                            <span class="badge {{ $badgeClass }}">
                                {{ $document['type'] ?? 'N/A' }}
                            </span>
                        </td>
                        <td class="text-center">
                            <span class="badge">
                                {{ $document['status'] ?? 'Ready' }}
                            </span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4" class="text-center">
                            No final documents listed.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">5. Super Admin Pages</div>

        <table class="documents-table">
            <thead>
                <tr>
                    <th style="width: 25%;">Page</th>
                    <th style="width: 60%;">Description</th>
                    <th style="width: 15%;">Type</th>
                </tr>
            </thead>

            <tbody>
                @forelse (($superAdminPages ?? []) as $page)
                    <tr>
                        <td><strong>{{ $page['title'] ?? 'N/A' }}</strong></td>
                        <td>{{ $page['description'] ?? 'N/A' }}</td>
                        <td class="text-center">
                            <span class="badge badge-page">
                                {{ $page['type'] ?? 'Page' }}
                            </span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center">
                            No Super Admin pages listed.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">6. Organizer / General Pages</div>

        <table class="documents-table">
            <thead>
                <tr>
                    <th style="width: 25%;">Page</th>
                    <th style="width: 60%;">Description</th>
                    <th style="width: 15%;">Type</th>
                </tr>
            </thead>

            <tbody>
                @forelse (($organizerPages ?? []) as $page)
                    <tr>
                        <td><strong>{{ $page['title'] ?? 'N/A' }}</strong></td>
                        <td>{{ $page['description'] ?? 'N/A' }}</td>
                        <td class="text-center">
                            @php
                                $type = strtolower($page['type'] ?? 'page');
                                $badgeClass = $type === 'pdf' ? 'badge-pdf' : 'badge-page';
                            @endphp

                            <span class="badge {{ $badgeClass }}">
                                {{ $page['type'] ?? 'Page' }}
                            </span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center">
                            No organizer pages listed.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section page-break">
        <div class="section-title">7. Final Submission Checklist</div>

        <table class="checklist-table">
            <thead>
                <tr>
                    <th style="width: 6%;">#</th>
                    <th style="width: 74%;">Checklist Item</th>
                    <th style="width: 20%;">Status</th>
                </tr>
            </thead>

            <tbody>
                @forelse (($submissionChecklist ?? []) as $index => $item)
                    <tr>
                        <td class="text-center">{{ $index + 1 }}</td>
                        <td>{{ $item['item'] ?? 'N/A' }}</td>
                        <td class="text-center">
                            <span class="badge">
                                {{ $item['status'] ?? 'Completed' }}
                            </span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center">
                            No checklist items listed.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">8. Recommended Final Demo Flow</div>

        <table class="flow-table">
            <thead>
                <tr>
                    <th style="width: 6%;">#</th>
                    <th style="width: 28%;">Step</th>
                    <th style="width: 66%;">Description</th>
                </tr>
            </thead>

            <tbody>
                @forelse (($demoFlow ?? []) as $index => $item)
                    <tr>
                        <td class="text-center">{{ $index + 1 }}</td>
                        <td><strong>{{ $item['step'] ?? 'N/A' }}</strong></td>
                        <td>{{ $item['description'] ?? 'N/A' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center">
                            No demo flow items listed.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">9. Final Remarks</div>

        <ul>
            @foreach (($finalRemarks ?? []) as $remark)
                <li>{{ $remark }}</li>
            @endforeach
        </ul>
    </div>

    <div class="section">
        <div class="section-title">10. Final Conclusion</div>

        <p>
            The Smart Event Invitation & Planning System is ready for final demonstration and submission.
            It includes core event management, guest management, public invitation links, RSVP workflow,
            check-in, follow-up, event planning modules, reminders, notifications, dashboards,
            activity logs, lifecycle protection, testing documentation, project handover documentation,
            and final PDF reports.
        </p>

        <p>
            The Master Final Submission Dashboard and Master Final Submission PDF provide a centralized
            final review point for the project. Future improvements can focus on production deployment,
            advanced invitation templates, automated email/SMS delivery, scheduler-based reminders,
            and enhanced analytics.
        </p>
    </div>

    <div class="footer">
        {{ $project['name'] ?? 'Smart Event Invitation & Planning System' }}
        | Master Final Submission PDF
    </div>
</body>
</html>
