<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Final Project Handover</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #111827;
            line-height: 1.5;
        }

        .header {
            text-align: center;
            border-bottom: 3px solid #111827;
            padding-bottom: 12px;
            margin-bottom: 18px;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 4px;
        }

        .subtitle {
            font-size: 13px;
            color: #4b5563;
        }

        .muted {
            color: #6b7280;
            font-size: 10px;
        }

        .section {
            margin-bottom: 18px;
            page-break-inside: avoid;
        }

        .section-title {
            font-size: 15px;
            font-weight: bold;
            background: #111827;
            color: #ffffff;
            padding: 7px 9px;
            margin-bottom: 8px;
        }

        .info-table,
        .stats-table,
        .access-table,
        .documents-table,
        .checklist-table {
            width: 100%;
            border-collapse: collapse;
        }

        .info-table td,
        .stats-table td,
        .access-table th,
        .access-table td,
        .documents-table th,
        .documents-table td,
        .checklist-table th,
        .checklist-table td {
            border: 1px solid #d1d5db;
            padding: 6px;
            vertical-align: top;
        }

        .label {
            font-weight: bold;
            background: #f3f4f6;
            width: 22%;
        }

        .stats-label {
            font-weight: bold;
            background: #f3f4f6;
            width: 25%;
        }

        .access-table th,
        .documents-table th,
        .checklist-table th {
            background: #f3f4f6;
            color: #111827;
            text-align: left;
        }

        .badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 20px;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
            background: #dcfce7;
            color: #166534;
        }

        .badge-pdf {
            background: #fee2e2;
            color: #991b1b;
        }

        .badge-page {
            background: #ede9fe;
            color: #5b21b6;
        }

        .readiness {
            border: 2px solid #16a34a;
            background: #f0fdf4;
            padding: 12px;
            border-radius: 6px;
        }

        .readiness-title {
            font-size: 15px;
            font-weight: bold;
            color: #166534;
            margin-bottom: 4px;
        }

        .module-group {
            border: 1px solid #d1d5db;
            margin-bottom: 10px;
            padding: 8px;
            background: #f9fafb;
        }

        .module-group-title {
            font-weight: bold;
            font-size: 13px;
            margin-bottom: 6px;
            color: #111827;
        }

        ul {
            margin-top: 4px;
            margin-bottom: 4px;
            padding-left: 20px;
        }

        li {
            margin-bottom: 3px;
        }

        .page-break {
            page-break-before: always;
        }

        .footer {
            margin-top: 24px;
            border-top: 1px solid #d1d5db;
            padding-top: 8px;
            font-size: 10px;
            color: #6b7280;
            text-align: center;
        }

        .text-center {
            text-align: center;
        }

        .small {
            font-size: 10px;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">Final Project Handover / Submission Summary</div>

        <div class="subtitle">
            {{ $project['name'] ?? 'Smart Event Invitation & Planning System' }}
        </div>

        <div class="muted">
            Generated At:
            {{ $generatedAt ? $generatedAt->format('Y-m-d h:i A') : 'N/A' }}

            @if (!empty($generatedBy))
                |
                Generated By:
                {{ $generatedBy->name ?? 'N/A' }}

                @if (!empty($generatedBy->email))
                    ({{ $generatedBy->email }})
                @endif
            @endif
        </div>
    </div>

    <div class="section">
        <div class="section-title">1. Project Overview</div>

        <table class="info-table">
            <tr>
                <td class="label">Project Name</td>
                <td>{{ $project['name'] ?? 'N/A' }}</td>
            </tr>

            <tr>
                <td class="label">Purpose</td>
                <td>{{ $project['purpose'] ?? 'N/A' }}</td>
            </tr>

            <tr>
                <td class="label">Local URL</td>
                <td>{{ $project['local_url'] ?? 'N/A' }}</td>
            </tr>

            <tr>
                <td class="label">Database</td>
                <td>{{ $project['database'] ?? 'N/A' }}</td>
            </tr>

            <tr>
                <td class="label">Environment</td>
                <td>{{ $project['environment'] ?? 'N/A' }}</td>
            </tr>

            <tr>
                <td class="label">Target Users</td>
                <td>
                    <ul>
                        @foreach (($project['target_users'] ?? []) as $userType)
                            <li>{{ $userType }}</li>
                        @endforeach
                    </ul>
                </td>
            </tr>

            <tr>
                <td class="label">Technology Stack</td>
                <td>
                    <ul>
                        @foreach (($project['tech_stack'] ?? []) as $tech)
                            <li>{{ $tech }}</li>
                        @endforeach
                    </ul>
                </td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">2. Final Readiness Status</div>

        <div class="readiness">
            <div class="readiness-title">
                {{ $readiness['status'] ?? 'N/A' }}
            </div>

            <div>
                {{ $readiness['message'] ?? 'N/A' }}
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">3. Database / System Summary</div>

        <table class="stats-table">
            <tr>
                <td class="stats-label">Total Events</td>
                <td>{{ $systemStats['total_events'] ?? 0 }}</td>

                <td class="stats-label">Draft Events</td>
                <td>{{ $systemStats['draft_events'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Active Events</td>
                <td>{{ $systemStats['active_events'] ?? 0 }}</td>

                <td class="stats-label">Completed Events</td>
                <td>{{ $systemStats['completed_events'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Cancelled Events</td>
                <td>{{ $systemStats['cancelled_events'] ?? 0 }}</td>

                <td class="stats-label">Total Users</td>
                <td>{{ $systemStats['total_users'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Guests</td>
                <td>{{ $systemStats['total_guests'] ?? 0 }}</td>

                <td class="stats-label">Total Invitations</td>
                <td>{{ $systemStats['total_invitations'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Questions</td>
                <td>{{ $systemStats['total_questions'] ?? 0 }}</td>

                <td class="stats-label">Total Answers</td>
                <td>{{ $systemStats['total_answers'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Tasks</td>
                <td>{{ $systemStats['total_tasks'] ?? 0 }}</td>

                <td class="stats-label">Total Expenses</td>
                <td>{{ $systemStats['total_expenses'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Vendors</td>
                <td>{{ $systemStats['total_vendors'] ?? 0 }}</td>

                <td class="stats-label">Total Schedules</td>
                <td>{{ $systemStats['total_schedules'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Staff</td>
                <td>{{ $systemStats['total_staff'] ?? 0 }}</td>

                <td class="stats-label">Total Reminders</td>
                <td>{{ $systemStats['total_reminders'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Reminder Logs</td>
                <td>{{ $systemStats['total_reminder_logs'] ?? 0 }}</td>

                <td class="stats-label">Total QA Checks</td>
                <td>{{ $systemStats['total_qa_checks'] ?? 0 }}</td>
            </tr>

            <tr>
                <td class="stats-label">Total Activity Logs</td>
                <td>{{ $systemStats['total_activity_logs'] ?? 0 }}</td>

                <td class="stats-label">Report Type</td>
                <td>Final Handover PDF</td>
            </tr>
        </table>
    </div>

    <div class="section page-break">
        <div class="section-title">4. Completed Modules</div>

        @foreach (($completedModules ?? []) as $moduleGroup)
            <div class="module-group">
                <div class="module-group-title">
                    {{ $moduleGroup['group'] ?? 'N/A' }}
                </div>

                <ul>
                    @foreach (($moduleGroup['items'] ?? []) as $item)
                        <li>{{ $item }}</li>
                    @endforeach
                </ul>
            </div>
        @endforeach
    </div>

    <div class="section">
        <div class="section-title">5. System Access Summary</div>

        <table class="access-table">
            <thead>
                <tr>
                    <th style="width: 20%;">Role / User Type</th>
                    <th style="width: 65%;">Access Description</th>
                    <th style="width: 15%;">Status</th>
                </tr>
            </thead>

            <tbody>
                @forelse (($accessSummary ?? []) as $item)
                    <tr>
                        <td><strong>{{ $item['role'] ?? 'N/A' }}</strong></td>
                        <td>{{ $item['access'] ?? 'N/A' }}</td>
                        <td class="text-center">
                            <span class="badge">
                                {{ $item['status'] ?? 'N/A' }}
                            </span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center">
                            No access summary found.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section page-break">
        <div class="section-title">6. Final Documents and Reports</div>

        <table class="documents-table">
            <thead>
                <tr>
                    <th style="width: 25%;">Document</th>
                    <th style="width: 60%;">Description</th>
                    <th style="width: 15%;">Type</th>
                </tr>
            </thead>

            <tbody>
                @forelse (($finalDocuments ?? []) as $document)
                    <tr>
                        <td><strong>{{ $document['title'] ?? 'N/A' }}</strong></td>
                        <td>{{ $document['description'] ?? 'N/A' }}</td>
                        <td class="text-center">
                            @php
                                $type = strtolower($document['type'] ?? 'page');
                                $badgeClass = $type === 'pdf' ? 'badge-pdf' : 'badge-page';
                            @endphp

                            <span class="badge {{ $badgeClass }}">
                                {{ $document['type'] ?? 'N/A' }}
                            </span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center">
                            No documents found.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">7. Deployment / Local Setup Notes</div>

        <table class="documents-table">
            <thead>
                <tr>
                    <th style="width: 25%;">Area</th>
                    <th style="width: 75%;">Description</th>
                </tr>
            </thead>

            <tbody>
                @forelse (($setupNotes ?? []) as $note)
                    <tr>
                        <td><strong>{{ $note['title'] ?? 'N/A' }}</strong></td>
                        <td>{{ $note['description'] ?? 'N/A' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="2" class="text-center">
                            No setup notes found.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section page-break">
        <div class="section-title">8. Final Handover Checklist</div>

        <table class="checklist-table">
            <thead>
                <tr>
                    <th style="width: 6%;">#</th>
                    <th style="width: 74%;">Checklist Item</th>
                    <th style="width: 20%;">Status</th>
                </tr>
            </thead>

            <tbody>
                @forelse (($handoverChecklist ?? []) as $index => $item)
                    <tr>
                        <td class="text-center">{{ $index + 1 }}</td>
                        <td>{{ $item['item'] ?? 'N/A' }}</td>
                        <td class="text-center">
                            <span class="badge">
                                {{ $item['status'] ?? 'N/A' }}
                            </span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center">
                            No handover checklist items found.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">9. Recommended Future Improvements</div>

        <ul>
            @foreach (($futureImprovements ?? []) as $item)
                <li>{{ $item }}</li>
            @endforeach
        </ul>
    </div>

    <div class="section">
        <div class="section-title">10. Final Conclusion</div>

        <p>
            The Smart Event Invitation & Planning System includes the major functional, reporting,
            documentation, testing, and Super Admin monitoring features required for final demonstration.
            The system supports organizers in creating events, managing invitations, collecting RSVP responses,
            tracking guest activity, planning event operations, monitoring reminders, generating reports,
            and reviewing system activity through Super Admin tools.
        </p>

        <p>
            Based on the completed modules and final testing documentation, the system is ready for project
            submission, demonstration, and handover. Future improvements can focus on production deployment,
            automated messaging, enhanced analytics, role-specific permissions, and advanced invitation templates.
        </p>
    </div>

    <div class="footer">
        {{ $project['name'] ?? 'Smart Event Invitation & Planning System' }}
        | Final Project Handover PDF
    </div>
</body>
</html>
