<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Super Admin System Report</title>

    <style>
        @page {
            margin: 28px 32px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #111827;
            line-height: 1.45;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #111827;
            padding-bottom: 14px;
            margin-bottom: 18px;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            color: #0f172a;
            margin-bottom: 5px;
        }

        .subtitle {
            font-size: 12px;
            color: #475569;
        }

        .section {
            margin-bottom: 18px;
            page-break-inside: avoid;
        }

        .section-title {
            background: #0f172a;
            color: #ffffff;
            padding: 7px 9px;
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 8px;
            border-radius: 4px;
        }

        .meta-table,
        .summary-table,
        .data-table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta-table td,
        .summary-table td,
        .data-table th,
        .data-table td {
            border: 1px solid #cbd5e1;
            padding: 6px;
            vertical-align: top;
        }

        .meta-label {
            background: #f1f5f9;
            font-weight: bold;
            width: 22%;
            color: #334155;
        }

        .summary-table td {
            width: 25%;
            text-align: center;
        }

        .summary-label {
            font-size: 9px;
            color: #64748b;
            text-transform: uppercase;
            font-weight: bold;
        }

        .summary-value {
            font-size: 17px;
            font-weight: bold;
            color: #0f172a;
            margin-top: 3px;
        }

        .data-table th {
            background: #f1f5f9;
            color: #334155;
            font-weight: bold;
            text-align: left;
        }

        .muted {
            color: #64748b;
            font-size: 10px;
        }

        .badge {
            display: inline-block;
            padding: 3px 6px;
            border-radius: 4px;
            color: #ffffff;
            font-size: 9px;
            font-weight: bold;
        }

        .badge-draft {
            background: #64748b;
        }

        .badge-active {
            background: #16a34a;
        }

        .badge-completed {
            background: #2563eb;
        }

        .badge-cancelled {
            background: #dc2626;
        }

        .badge-action {
            background: #3730a3;
        }

        .remarks {
            border: 1px dashed #94a3b8;
            background: #f8fafc;
            padding: 10px;
            border-radius: 5px;
            color: #334155;
        }

        .footer-note {
            margin-top: 18px;
            padding-top: 10px;
            border-top: 1px solid #cbd5e1;
            text-align: center;
            font-size: 9px;
            color: #64748b;
        }

        .page-break {
            page-break-before: always;
        }

        .text-right {
            text-align: right;
        }

        .small {
            font-size: 10px;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">Super Admin System Report</div>
        <div class="subtitle">Smart Event Invitation & Planning System</div>
        <div class="subtitle">
            Generated on {{ $generatedAt?->format('Y-m-d H:i') }}
        </div>
    </div>

    <div class="section">
        <div class="section-title">Report Information</div>

        <table class="meta-table">
            <tr>
                <td class="meta-label">Generated By</td>
                <td>
                    {{ $generatedBy?->name ?? 'N/A' }}
                    @if (!empty($generatedBy?->email))
                        <br>
                        <span class="muted">{{ $generatedBy->email }}</span>
                    @endif
                </td>

                <td class="meta-label">Generated At</td>
                <td>{{ $generatedAt?->format('Y-m-d H:i') }}</td>
            </tr>

            <tr>
                <td class="meta-label">Report Type</td>
                <td>System-wide Super Admin Report</td>

                <td class="meta-label">Scope</td>
                <td>Events, users, guests, invitations, QA, and activity logs</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">System Summary</div>

        <table class="summary-table">
            <tr>
                <td>
                    <div class="summary-label">Total Events</div>
                    <div class="summary-value">{{ $summary['total_events'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">Total Users</div>
                    <div class="summary-value">{{ $summary['total_users'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">Organizers</div>
                    <div class="summary-value">{{ $summary['organizers'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">Super Admins</div>
                    <div class="summary-value">{{ $summary['super_admins'] ?? 0 }}</div>
                </td>
            </tr>

            <tr>
                <td>
                    <div class="summary-label">Guests</div>
                    <div class="summary-value">{{ $summary['total_guests'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">Invitations</div>
                    <div class="summary-value">{{ $summary['total_invitations'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">RSVP Questions</div>
                    <div class="summary-value">{{ $summary['total_questions'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">RSVP Answers</div>
                    <div class="summary-value">{{ $summary['total_answers'] ?? 0 }}</div>
                </td>
            </tr>

            <tr>
                <td>
                    <div class="summary-label">QA Checks</div>
                    <div class="summary-value">{{ $summary['total_qa_checks'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">Activity Logs</div>
                    <div class="summary-value">{{ $summary['total_activity_logs'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">This Week Logs</div>
                    <div class="summary-value">{{ $summary['this_week_logs'] ?? 0 }}</div>
                </td>

                <td>
                    <div class="summary-label">This Month Logs</div>
                    <div class="summary-value">{{ $summary['this_month_logs'] ?? 0 }}</div>
                </td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Events by Status</div>

        <table class="data-table">
            <thead>
                <tr>
                    <th>Status</th>
                    <th class="text-right">Count</th>
                    <th class="text-right">Percentage</th>
                </tr>
            </thead>

            <tbody>
                @php
                    $totalEvents = max((int) ($summary['total_events'] ?? 0), 1);
                @endphp

                @foreach ($eventsByStatus as $item)
                    @php
                        $status = $item['status'] ?? 'draft';
                        $percentage = round((($item['count'] ?? 0) / $totalEvents) * 100, 2);
                    @endphp

                    <tr>
                        <td>
                            <span class="badge badge-{{ $status }}">
                                {{ $item['label'] ?? ucfirst($status) }}
                            </span>
                        </td>
                        <td class="text-right">{{ $item['count'] ?? 0 }}</td>
                        <td class="text-right">{{ $percentage }}%</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Monthly Event Creation</div>

        @if (!empty($monthlyEvents))
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Month</th>
                        <th class="text-right">Events Created</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($monthlyEvents as $item)
                        <tr>
                            <td>{{ $item['month'] ?? 'N/A' }}</td>
                            <td class="text-right">{{ $item['count'] ?? 0 }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p class="muted">No monthly event creation data available.</p>
        @endif
    </div>

    <div class="section">
        <div class="section-title">Top Organizers by Event Count</div>

        @if (!empty($topOrganizers))
            <table class="data-table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Organizer</th>
                        <th>Email</th>
                        <th class="text-right">Events</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($topOrganizers as $index => $organizer)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $organizer['name'] ?? 'N/A' }}</td>
                            <td>{{ $organizer['email'] ?? 'N/A' }}</td>
                            <td class="text-right">{{ $organizer['events_count'] ?? 0 }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p class="muted">No organizer data available.</p>
        @endif
    </div>

    <div class="page-break"></div>

    <div class="section">
        <div class="section-title">Recent Events</div>

        @if (!empty($recentEvents))
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Event</th>
                        <th>Organizer</th>
                        <th>Date</th>
                        <th>Venue</th>
                        <th>Status</th>
                        <th>Created</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($recentEvents as $event)
                        @php
                            $status = $event['status'] ?? 'draft';
                        @endphp

                        <tr>
                            <td>
                                <strong>{{ $event['title'] ?? 'N/A' }}</strong>
                                <br>
                                <span class="muted">
                                    Type: {{ $event['event_type'] ?? 'N/A' }}
                                </span>
                            </td>

                            <td>
                                {{ $event['organizer_name'] ?? 'N/A' }}
                                <br>
                                <span class="muted">{{ $event['organizer_email'] ?? '' }}</span>
                            </td>

                            <td>
                                {{ $event['event_date'] ?? 'N/A' }}
                                @if (!empty($event['event_time']))
                                    <br>
                                    <span class="muted">{{ $event['event_time'] }}</span>
                                @endif
                            </td>

                            <td>{{ $event['venue'] ?? 'N/A' }}</td>

                            <td>
                                <span class="badge badge-{{ $status }}">
                                    {{ ucfirst($status) }}
                                </span>
                            </td>

                            <td>{{ $event['created_at'] ?? 'N/A' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p class="muted">No recent events available.</p>
        @endif
    </div>

    <div class="section">
        <div class="section-title">Recent Activity Logs</div>

        @if (!empty($recentActivityLogs))
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Action</th>
                        <th>Event</th>
                        <th>User</th>
                        <th>Description</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($recentActivityLogs as $log)
                        <tr>
                            <td>{{ $log['created_at'] ?? 'N/A' }}</td>

                            <td>
                                <span class="badge badge-action">
                                    {{ $log['action'] ?? 'N/A' }}
                                </span>
                            </td>

                            <td>
                                {{ $log['event_title'] ?? 'N/A' }}
                                @if (!empty($log['event_status']))
                                    <br>
                                    <span class="muted">
                                        {{ ucfirst($log['event_status']) }}
                                    </span>
                                @endif
                            </td>

                            <td>
                                {{ $log['user_name'] ?? 'System' }}
                                @if (!empty($log['user_email']))
                                    <br>
                                    <span class="muted">{{ $log['user_email'] }}</span>
                                @endif
                            </td>

                            <td>{{ $log['description'] ?? 'N/A' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p class="muted">No recent activity logs available.</p>
        @endif
    </div>

    <div class="section">
        <div class="section-title">System Remarks</div>

        <div class="remarks">
            <p>
                This report summarizes the current operational state of the Smart Event Invitation & Planning System.
                It includes system-wide event, user, RSVP, QA, and activity log information for Super Admin review.
            </p>

            <p>
                Recommended Super Admin workflow:
                Super Admin Dashboard → Manage All Events → Manage Users → Activity Logs → System Report PDF.
            </p>
        </div>
    </div>

    <div class="footer-note">
        This document was generated by the Smart Event Invitation & Planning System.
    </div>
</body>
</html>
